### 상품 목록 조회 (최신순, 기본)
GET {{commerce-api}}/api/v1/products?sort=latest&page=0&size=20

### 상품 목록 조회 (좋아요 내림차순)
GET {{commerce-api}}/api/v1/products?sort=likes_desc&page=0&size=20

### 상품 목록 조회 (좋아요 오름차순)
GET {{commerce-api}}/api/v1/products?sort=likes_asc&page=0&size=20

### 상품 목록 조회 (가격 오름차순)
GET {{commerce-api}}/api/v1/products?sort=price_asc&page=0&size=20

### 상품 목록 조회 (가격 내림차순)
GET {{commerce-api}}/api/v1/products?sort=price_desc&page=0&size=20

### 브랜드 필터 + 최신순
GET {{commerce-api}}/api/v1/products?brandId=5&sort=latest&page=0&size=20

### 브랜드 필터 + 좋아요 내림차순
GET {{commerce-api}}/api/v1/products?brandId=5&sort=likes_desc&page=0&size=20

### 브랜드 필터 + 가격 오름차순
GET {{commerce-api}}/api/v1/products?brandId=5&sort=price_asc&page=0&size=20

### 상품 상세 조회
GET {{commerce-api}}/api/v1/products/1
