spring:
  main:
    web-application-type: none
  application:
    name: commerce-batch
  profiles:
    active: local
  config:
    import:
      - jpa.yml
      - redis.yml
      - logging.yml
      - monitoring.yml
  batch:
    job:
      name: ${job.name:NONE}
      enabled: false
    jdbc:
      initialize-schema: never

batch:
  snapshot:
    daily:
      chunk-size: 500
      skip-limit: 100
      retry-limit: 3
      ttl-warn-threshold-hours: 12
  ranking:
    orchestrator:
      cron: "0 0 1 * * *"
    weight:
      view: 0.1
      like: 0.2
      order: 0.6
    weekly:
      chunk-size: 50
      skip-limit: 10
      retry-limit: 3
      top-n: 100
    monthly:
      chunk-size: 50
      skip-limit: 10
      retry-limit: 3
      top-n: 100

management:
  health:
    defaults:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: local, test
  batch:
    jdbc:
      initialize-schema: always

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: qa

---
spring:
  config:
    activate:
      on-profile: prd

springdoc:
  api-docs:
    enabled: false