-- =============================================================
-- 랭킹 메트릭 시뮬레이션 데이터 생성 스크립트
-- 전제: seed-test-data.sql 실행 완료 (brands 50K, users 100K, products 1M)
-- 결과: ranking_metric ~810만 건 (300K 상품 × 90일 × 30% 활성률)
-- =============================================================

-- 기존 데이터 삭제
DELETE FROM ranking_metric;

-- seq_helper 생성 (0~9999)
DROP TABLE IF EXISTS seq_helper;
CREATE TABLE seq_helper (n INT PRIMARY KEY);
SET cte_max_recursion_depth = 10000;
INSERT INTO seq_helper (n)
WITH RECURSIVE cte AS (
    SELECT 0 AS n UNION ALL SELECT n + 1 FROM cte WHERE n < 9999
)
SELECT n FROM cte;
COMMIT;

-- =============================================================
-- 배치 1~10: 상품 1~100,000
-- =============================================================
SET autocommit = 0;
SET unique_checks = 0;

INSERT INTO ranking_metric (product_id, ranking_date, total_score, event_count, created_at, updated_at)
SELECT
    (batch.b * 10000) + seq.n + 1 as product_id,
    DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL d.day_offset DAY), '%Y%m%d') as ranking_date,
    ROUND(RAND(((batch.b * 10000) + seq.n) * 90 + d.day_offset + 1) * 10000, 2) as total_score,
    FLOOR(RAND(((batch.b * 10000) + seq.n) * 90 + d.day_offset + 2) * 1000) as event_count,
    NOW(), NOW()
FROM seq_helper seq
CROSS JOIN (SELECT 0 AS b UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4
            UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) batch
CROSS JOIN (
    SELECT 0 AS day_offset UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4
    UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9
    UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14
    UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19
    UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24
    UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29
    UNION SELECT 30 UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34
    UNION SELECT 35 UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39
    UNION SELECT 40 UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44
    UNION SELECT 45 UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49
    UNION SELECT 50 UNION SELECT 51 UNION SELECT 52 UNION SELECT 53 UNION SELECT 54
    UNION SELECT 55 UNION SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59
    UNION SELECT 60 UNION SELECT 61 UNION SELECT 62 UNION SELECT 63 UNION SELECT 64
    UNION SELECT 65 UNION SELECT 66 UNION SELECT 67 UNION SELECT 68 UNION SELECT 69
    UNION SELECT 70 UNION SELECT 71 UNION SELECT 72 UNION SELECT 73 UNION SELECT 74
    UNION SELECT 75 UNION SELECT 76 UNION SELECT 77 UNION SELECT 78 UNION SELECT 79
    UNION SELECT 80 UNION SELECT 81 UNION SELECT 82 UNION SELECT 83 UNION SELECT 84
    UNION SELECT 85 UNION SELECT 86 UNION SELECT 87 UNION SELECT 88 UNION SELECT 89
) d
WHERE seq.n < 10000
  AND RAND(((batch.b * 10000) + seq.n) * 90 + d.day_offset) < 0.30;
COMMIT;

-- =============================================================
-- 배치 11~20: 상품 100,001~200,000
-- =============================================================
INSERT INTO ranking_metric (product_id, ranking_date, total_score, event_count, created_at, updated_at)
SELECT
    (batch.b * 10000) + seq.n + 1 as product_id,
    DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL d.day_offset DAY), '%Y%m%d') as ranking_date,
    ROUND(RAND(((batch.b * 10000) + seq.n) * 90 + d.day_offset + 1) * 10000, 2) as total_score,
    FLOOR(RAND(((batch.b * 10000) + seq.n) * 90 + d.day_offset + 2) * 1000) as event_count,
    NOW(), NOW()
FROM seq_helper seq
CROSS JOIN (SELECT 10 AS b UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14
            UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19) batch
CROSS JOIN (
    SELECT 0 AS day_offset UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4
    UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9
    UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14
    UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19
    UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24
    UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29
    UNION SELECT 30 UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34
    UNION SELECT 35 UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39
    UNION SELECT 40 UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44
    UNION SELECT 45 UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49
    UNION SELECT 50 UNION SELECT 51 UNION SELECT 52 UNION SELECT 53 UNION SELECT 54
    UNION SELECT 55 UNION SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59
    UNION SELECT 60 UNION SELECT 61 UNION SELECT 62 UNION SELECT 63 UNION SELECT 64
    UNION SELECT 65 UNION SELECT 66 UNION SELECT 67 UNION SELECT 68 UNION SELECT 69
    UNION SELECT 70 UNION SELECT 71 UNION SELECT 72 UNION SELECT 73 UNION SELECT 74
    UNION SELECT 75 UNION SELECT 76 UNION SELECT 77 UNION SELECT 78 UNION SELECT 79
    UNION SELECT 80 UNION SELECT 81 UNION SELECT 82 UNION SELECT 83 UNION SELECT 84
    UNION SELECT 85 UNION SELECT 86 UNION SELECT 87 UNION SELECT 88 UNION SELECT 89
) d
WHERE seq.n < 10000
  AND RAND(((batch.b * 10000) + seq.n) * 90 + d.day_offset) < 0.30;
COMMIT;

-- =============================================================
-- 배치 21~29: 상품 200,001~300,000
-- =============================================================
INSERT INTO ranking_metric (product_id, ranking_date, total_score, event_count, created_at, updated_at)
SELECT
    (batch.b * 10000) + seq.n + 1 as product_id,
    DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL d.day_offset DAY), '%Y%m%d') as ranking_date,
    ROUND(RAND(((batch.b * 10000) + seq.n) * 90 + d.day_offset + 1) * 10000, 2) as total_score,
    FLOOR(RAND(((batch.b * 10000) + seq.n) * 90 + d.day_offset + 2) * 1000) as event_count,
    NOW(), NOW()
FROM seq_helper seq
CROSS JOIN (SELECT 20 AS b UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24
            UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29) batch
CROSS JOIN (
    SELECT 0 AS day_offset UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4
    UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9
    UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14
    UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19
    UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24
    UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29
    UNION SELECT 30 UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34
    UNION SELECT 35 UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39
    UNION SELECT 40 UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44
    UNION SELECT 45 UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49
    UNION SELECT 50 UNION SELECT 51 UNION SELECT 52 UNION SELECT 53 UNION SELECT 54
    UNION SELECT 55 UNION SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59
    UNION SELECT 60 UNION SELECT 61 UNION SELECT 62 UNION SELECT 63 UNION SELECT 64
    UNION SELECT 65 UNION SELECT 66 UNION SELECT 67 UNION SELECT 68 UNION SELECT 69
    UNION SELECT 70 UNION SELECT 71 UNION SELECT 72 UNION SELECT 73 UNION SELECT 74
    UNION SELECT 75 UNION SELECT 76 UNION SELECT 77 UNION SELECT 78 UNION SELECT 79
    UNION SELECT 80 UNION SELECT 81 UNION SELECT 82 UNION SELECT 83 UNION SELECT 84
    UNION SELECT 85 UNION SELECT 86 UNION SELECT 87 UNION SELECT 88 UNION SELECT 89
) d
WHERE seq.n < 10000
  AND RAND(((batch.b * 10000) + seq.n) * 90 + d.day_offset) < 0.30;
COMMIT;

-- =============================================================
-- 정리 및 검증
-- =============================================================
SET autocommit = 1;
SET unique_checks = 1;
DROP TABLE IF EXISTS seq_helper;

SELECT COUNT(*) as total_rows,
       COUNT(DISTINCT product_id) as distinct_products,
       COUNT(DISTINCT ranking_date) as distinct_dates,
       MIN(ranking_date) as min_date,
       MAX(ranking_date) as max_date
FROM ranking_metric;
